### ISSUE TITLE
default_date в multiple

### ISSUE THREAD

**Issue by djAlba** [nazar-pc/PickMeUp#121]
<input type='text' id='cal_<?=$calname;?>' name='<?=$calname;?>' style='width: 300px' placeholder='укажите даты'>
$("#cal_<?=$calname;?>").pickmeup({format: 'Y-m-d', mode: 'multiple', default_date: false, separator: ','});

есть элемент input, не могу добиться, чтобы при открытии календаря не выбиралась по-умолчанию сегодняшняя дата. приходится выбирать даты, потом "отжимать" текущую дату. вроде-же было заявлено, что пофиксено?

**Comment by nazar-pc** [comment]
Any more details, demo?
https://github.com/nazar-pc/PickMeUp#contribution

**Comment by djAlba** [comment]
example is here: https://partytown.ru/pickmeup.php
if i click on input, calendar is displayed, and today is selected "by default". when i click any day, in input shows two dates - today and selected

**Comment by nazar-pc** [comment]
Because it is `multiple` mode, it selects 1, 2, 3, 4... any number of dates.
What did you expected?

**Comment by djAlba** [comment]
For example, i want to select all saturdays in next month (3.09, 10.09, 17.09, 24.09).
i click to input, calendar opens, i click on ">" to change month to september, and begins to click on saturdays. when i select first day (3 september), in input displayed "2016-08-05,2016-09-03" - today date and my selected day.
in config - "default_date: false"

**Comment by nazar-pc** [comment]
OK, then once again: https://github.com/nazar-pc/PickMeUp#contribution
Prepare standalone simple demo first and I'll take a look at it.

**Comment by djAlba** [comment]
my example: https://jsfiddle.net/ws8a8ffy/

**Comment by djAlba** [comment]
any ideas?

**Comment by djAlba** [comment]
any ideas?

**Comment by nazar-pc** [comment]
Confirmed to be a bug, will work on it.

**Comment by nazar-pc** [comment]
Your example is not exactly correct as for what you want you have to also specify empty array of dates so that nothing is selected by default (`default_date` only affects value in `<input>), but there was also a problem in PickMeUp itself, which should now be fixes.
So correct example I believe would be this (uses current master branch code): https://jsfiddle.net/ws8a8ffy/1/

There was a lot of changes recently, test it thoroughly from master branch before I release new version. New version will also address some other significant issues.
