### ISSUE TITLE
Twitter bootstrap integration

### ISSUE THREAD

**Issue by ErazerBrecht** [nazar-pc/PickMeUp#138]
It seems this doesn't work anymore.
- pickmeup doesn't get changed to: pickmeup-twitter-bootstrap well
- The generated html isn't placed in the correct target (instead placed on the bottom of the HTML)
- pmu-hidden is still on the container

I'm quite sure this problems are correlated. I tried to debug it to see where is goes wrong, but I didn't find it.

**Comment by nazar-pc** [comment]
I'm not actively using it, so it might be broken.
Will take a look.
What it basically does is following:
* change root class, so that default styling doesn't apply
* instantiate few TB-specific elements to compute their styles
* get styles and generate new stylesheet with TB-specific styles
* insert new stylesheet into document

**Comment by nazar-pc** [comment]
Could you take a look at 5bdc4d7? It should fix this issue.

**Comment by ErazerBrecht** [comment]
Will check it this weekend.

Thank you in advance.
