### ISSUE TITLE
Minimum selected days option

### ISSUE THREAD

**Issue by select-lewis-knight** [nazar-pc/PickMeUp#143]
Firstly i'd like to say great plugin! So easy to use and easy to customise.

Can i suggest an extra feature that may help future developers?

## mode: "range":
Having a **min_select_days**(int) that will disable days after the first selected date. For example if I chose 20/09/2016 and my **min_select_days** was 4, it would disable the 21st and 22nd of that selected month and everything there after was clickable.

Thanks,

Lew.

**Comment by nazar-pc** [comment]
This is very specific use case. PickMeUp can't possibly support any such use case, but it tries to provide building blocks so that you can implement it yourself.

Your feature is already possible with current version of the plugin:
* listen for `pickmeup-change` even and remember selected dates
* in `render` options specify function that will mark as disabled dates you want depending on what was selected in `pickmeup-change` event
