### ISSUE TITLE
Add classes to end and start date in range mode

### ISSUE THREAD

**Issue by ceephax** [nazar-pc/PickMeUp#170]
This would be handy so that I can style the start and end dates differently from the rest of the range.

**Comment by nazar-pc** [comment]
Start end end of what?

**Comment by ceephax** [comment]
Like this:
![pmu](https://cloud.githubusercontent.com/assets/10236690/25710887/81cae18c-30e5-11e7-8ffe-464c073d9805.PNG)

Although if the range crossed multiple calendars/months the last class should be on the very last instance of the range.

**Comment by nazar-pc** [comment]
It is already possible with current set of events and callbacks PickMeUp provides to the developer: https://jsfiddle.net/rnnrewwc/
Yes, it is a bit of code, but there are more use cases and I'd like to enable people to achieve them without editing PickMeUp's source code rather than implementing everything in the core.

**Comment by niteshkumar-singh** [comment]
After doing this if pickmeup('.date').clear(); use to clear then its show this error:

index.html:50 Uncaught TypeError: Cannot read property 'valueOf' of undefined
    at Object.render (index.html:50)
    at pickmeup.min.js:489
    at HTMLInputElement.fill (pickmeup.min.js:524)
    at HTMLInputElement.clear (pickmeup.min.js:1027)
    at <anonymous>:1:20

**Comment by nazar-pc** [comment]
I have no idea why it happens without any demo
