### ISSUE TITLE
range in months or years

### ISSUE THREAD

**Issue by lica667** [nazar-pc/PickMeUp#72]
Hello. I use range mode. and now I need select range by selecting months or years. Can I do this?

**Comment by nazar-pc** [comment]
Do you need to select only months or years without days at all?
Have you tried to set `select_day` to `false`?

**Comment by lica667** [comment]
I need days, months, years

**Comment by nazar-pc** [comment]
So what is wrong? Selection just works, click on day, move to another month, click another day.

**Comment by lica667** [comment]
I mean not select day when select months:
for example, i need select 1.02.2015 - 1.05.2015
And can I just click feb. then click may and calendar selected this range?

**Comment by nazar-pc** [comment]
Yes, it is possible, but not out of the box. You can implement this yourself by catching click on month.
This is not widely used feature since you're the first who is asking exactly this, that is why it was not implemented yet.
This is actually saves only two clicks on range selection in general, I have no idea why you need this.

**Comment by lica667** [comment]
It's hard to explain. but thank you for answering

**Comment by nazar-pc** [comment]
No problem, good luck)
