### ISSUE TITLE
Add "alter_text" function

### ISSUE THREAD

**Issue by ddrozdik** [nazar-pc/PickMeUp#98]
This library works great, thank you, but I faced a situation that I need an additional function "alter_text" which will provide possibility add some modifications to the "day" object, especially I need to have ability modify text value. I suppose this additional feature will be helpful, and will add more flexibility to this library.

**Comment by DmitryDrozdik** [comment]
I have prepared  a pull request https://github.com/nazar-pc/PickMeUp/pull/99. Please review it.

**Comment by nazar-pc** [comment]
What exactly use case do you have that you can't achieve with current implementation?
Demo would be useful.

**Comment by DmitryDrozdik** [comment]
Looks like this is not fully good solution that I made in the PR. 

My use case is next: I use this library for creating some kind of calendar with information about events. Here is an example https://gyazo.com/4a9983bf87fc5301a4e6dbe55066a088 and as you can see I have added some html to the box with number of the day. Out of the box this solution is not working, because this library use .text() value here https://github.com/nazar-pc/PickMeUp/blob/master/js/jquery.pickmeup.js#L686 , and if add some html inside of the box, then library will not work correctly. 

But I see that this solution could work if use data attribute for storing information about day number, instead of using text value. 

What do you think about this ?

**Comment by nazar-pc** [comment]
To be honest your particular example can be solved by attaching classes to dates and generating CSS for them on-fly. You have one thing before day number and one after - so `:before` and `:after` should be enough.
After thinking about it for a while my suggestion would be to:
1. Use data attributes or other alternative to store number
2. Allow to modify content/additional properties other than `class` in `render` event or just allow to customize `tpl` variable, which currently is not available outside

What you think?

**Comment by DmitryDrozdik** [comment]
Yeah, in 90% of cases classes are good, but when you need add some text inside of the box, for example in case when you need display a tooltip on hover of the day box, then classes will not work.  

I suggest you use next way:
1. Work with data-attribute instead of getting day value using `.text()` method. In this case you always will have correct value, and will not have dependency on text value.
2. Allow to customize variable that contain text/html for a day box. And maybe also `tpl` variable.

What do you think?
I can help with these changes if you are agree with my suggestion.

**Comment by nazar-pc** [comment]
I think you understood correctly, that would be the way I'd like to see it.

**Comment by nazar-pc** [comment]
Any update on this topic?

**Comment by DmitryDrozdik** [comment]
I did not have a chance to finalize it. I have applied needed for me changes, but did not prepared a patch. I want to review, and maybe modify applied solution. Hope will do this soon.

**Comment by nazar-pc** [comment]
New build in master branch (which is still under development and is completely jQuery-free) allows you to customize contents of any Year/Month/Day element in any way you like by re-defining new option `instance_content_template` (copy it from sources and modify any way you like). You can even put videos or iframes there is there is a need for it!
